name: PlayerSlap
main: me.PlayerSlap.MainClasses.PlayerSlapMainClasses 
version: development_0.0.0.0  
description: A plugin to slap players  
author: aappleton3 
database: false
commands:
  slap:
    description: Command to slap a player 
    usage: /slap [<player>] [<type>] [<worth>]
    aliases: [sl, hit]
    permission-message: You do not have the required permissions to perform this command 
  slapall:
    description: Command to slap every layer 
    usage: /slapall [<type>] [<worth>]
    aliases: [sla, slap-all]
    permission-message: You do not have the required permissions to perform this command 
  forceslap:
    description: Slap Players with the playerslap.noslap permission 
    usage: /forceslap <player> [<type>] [<worth>]
    aliases: [fs, fosla]
    permission-message: You do not have the required permissions to perform this command 
  slapaccept:
    description: Acknowledge that you have been slapped if someone slaps you 
    usage: /slapaccept [<player>] 
    aliases: [slapac, slaa, slacc]
    permission-message: You do not have the required permissions to perform this command 
  slaprelease:
    description: Release a player who has been hit with a permanent slap 
    usage: /slaprelease <player>
    aliases: [slaprel, slarel, slrel]
    permission-message: You do not have the required permissions to perform this command 
  slapinfo:
    description: Get information about players and lap types 
    usage: /slapinfo slaplist|{slap <type>}|{slapmessages <type>}|{slapmobs <type>}|{player <player>}|{times <player>}|general
    aliases: [slai, slapi, sli]
    permission-message: You do not have the required permissions to perform this command 
  playerslap:
    description: The base informative command for the PlayerSlap plugin 
    usage: /playerslap help|version|{config save|reload|{set <type> <property> <value>}|{new <type>}|{remove <type>}}|{player}
    aliases: [ps, plasl, plasla]
    permission-message: You do not have the required permissions to perform this command 
permissions:
  playerslap.*:
    description: Give the player every PlayerSlap permission 
    default: op
    children:
      playerslap.slap.all: true
      playerslap.accept.others: true
      playerslap.release: true
      playerslap.times.*: true
      playerslap.force: true
      playerslap.noslap.protect: true
      playerslap.see.*: true
      playerslap.config.*: true
      playerslap.info.*: true
      playerslap.type.*: true
  playerslap.slap.all:
    description: Give the player permission to slap every player 
    default: op
    children:
      playerslap.slap.others: true
  playerslap.slap.others:
    description: Give the player permission to slap other players 
    default: op
    children:
      playerslap.slap: true
  playerslap.slap:
    description: Give the player permission to slap itself
    default: op
  playerslap.accept.others:
    description: Give the player permission to acknowledge that another player has been slapped 
    default: op
    children:
      playerslap.accept: true
  playerslap.accept:
    description: Let the player ackniwledge that it has been slapped
    default: op
  playerslap.release:
    description: Release a player who has had a permenant slap 
    default: op
  playerslap.times.*:
    description: Give the player to see how many times players have been slapped and reset them 
    default: op
    children: 
      playerslap.times.reset: true
      playerslap.times.others: true
  playerslap.times.reset: 
    description: Reset the amount of times a player has been slapped 
    default: op
  playerslap.times.others:
    description: Give the player permission to see how many times other players have been slapped 
    default: op
    children:
      playerslap.times: true
  playerslap.times:
    description: Give the player permission to see how many times it has been slapped 
    default: op
  playerslap.force:
    description: Give the player permission to use the /forceslap command 
    default: op
  playerslap.noslap.protect:
    description: Slap any player who tries to slap the player with this permission 
    default: op
    children:
      playerslap.noslap: true
  playerslap.noslap:
    description: Prevent a player from being slapped 
    default: op
  playerslap.see.*:
    description: Give the player permission to see all PlayerSlap messages 
    default: op
    children:
      playerslap.see.slap: true
      playerslap.see.noslap: true
      playerslap.see.accept: true
      playerslap.see.release: true
      playerslap.see.config: true
  playerslap.see.slap:
    description: Give the player permission to see when a player has been slapped
    default: op
  playerslap.see.noslap:
    description: Give the player permission to see when a player tried to slap a player with the playerslap.noslap permission
    default: op
  playerslap.see.accept:
    description: Give the player permission to see a player's response to a slap 
    default: op
  playerslap.see.release:
    description: Give the player permission to see when a player is released from a permenant slap 
    default: op
  playerslap.see.config:
    description: Give the player permission to see config save, set and reload messages 
    default: op
  playerslap.config.*:
    description: Give the player access to all config file commands 
    default: op
    children: 
      playerslap.config.save: true
      playerslap.config.reload: true
      playerslap.config.set.* : true
  playerslap.config.save:
    description: Save the config file 
    default: op
  playerslap.config.reload:
    description: Reload the config file 
    default: op
  playerslap.config.set.*:
    description: Set basic config file options 
    default: op
  playerslap.info.*:
    description: Get information about slap types, players and general config information 
    default: op
    children:
      playerslap.info.slap: true
      playerslap.info.slapmessages: true
      playerslap.info.slapmobs: true
      playerslap.info.slaplist: true
      playerslap.info.player: true
      playerslap.info.general: true
  playerslap.info.slap:
    description: Get information on a type of slap 
    default: op
  playerslap.info.slapmessages:
    description: The slap specific messages sent by a slap 
    default: op
  playerslap.info.slapmobs:
    description: The mobs spawned by a slap 
    default: op
  playerslap.info.slaplist:
    description: List the available slap types 
    default: op
  playerslap.info.player:
    description: Get information on a player 
    default: op
    children:
      playerslap.info.player.times: true
  playerslap.info.player.times:
    description: Get the number of times a player has been slapped 
    default: op
  playerslap.info.general:
    description: Get general config file information 
    default: op
  playerslap.type.*:
    description: Use every slap 
    default: op
    children:
      playerslap.type.worth.*: true
      playerslap.type.noworth.*: true
  playerslap.type.anyworth.*:
    description: Use every slap with any positive worth value
    default: op
  playerslap.type.defaultworth.*:
    description: Use every slap with its specified 'worth' value 
    default: op
  playerslap.type.noworth.*:
    description: Use every slap with a 'worth' value of 0
    default: op
