name: PlayerSlap
main: me.PlayerSlap.MainClasses.PlayerSlapMainClass
version: Development_0.0.0.2
description: A plugin to slap players  
author: aappleton3 
database: false
commands:
  slap:
    description: Command to slap a player 
    usage: /slap [<player>] [<type>] [<worth>]
    aliases: [sl, hit]
    permission-message: You do not have the required permissions to perform this command 
  slapall:
    description: Command to slap every layer 
    usage: /slapall [<type>] [<worth>]
    aliases: [sla, slap-all]
    permission-message: You do not have the required permissions to perform this command 
  forceslap:
    description: Slap Players with the playerslap.noslap permission 
    usage: /forceslap <player> [<type>] [<worth>]
    aliases: [fs, fosla]
    permission-message: You do not have the required permissions to perform this command 
  slapaccept:
    description: Acknowledge that you have been slapped if someone slaps you 
    usage: /slapaccept [<player>] 
    aliases: [slapac, slaa, slacc]
    permission-message: You do not have the required permissions to perform this command 
  slaprelease:
    description: Release a player who has been hit with a permanent slap 
    usage: /slaprelease <player>
    aliases: [slaprel, slarel, slrel]
    permission-message: You do not have the required permissions to perform this command 
  slapinfo:
    description: Get information about players and lap types 
    usage: /slapinfo slaplist|{slap <type>}|{slapmessages <type>}|{slapmobs <type>}|{player <player>}|{times <player>}|general
    aliases: [slai, slapi, sli]
    permission-message: You do not have the required permissions to perform this command 
  playerslap:
    description: The base informative command for the PlayerSlap plugin 
    usage: /playerslap help|version|{config save|reload|{set <property> <value>}}|{slap {set <type> <property> [sub-property] <value>}|{new <type>}|{remove <type>}}|{player {set <player> <property> <value> [<modifier>]}|{remove <player>}}
    aliases: [ps, plasl, plasla]
    permission-message: You do not have the required permissions to perform this command 
permissions:
  playerslap.*:
    description: Give the player every PlayerSlap permission 
    default: op
    children:
      playerslap.slap.all: true
      playerslap.accept.others: true
      playerslap.release: true
      playerslap.force: true
      playerslap.noslap.protect: true
      playerslap.see.*: true
      playerslap.unslap.*: true
      playerslap.config.*: true
      playerslap.info.*: true
      playerslap.type.*: true
  playerslap.slap.all:
    description: Give the player permission to slap every player 
    default: op
    children:
      playerslap.slap.others: true
  playerslap.slap.others:
    description: Give the player permission to slap other players 
    default: op
    children:
      playerslap.slap: true
  playerslap.slap:
    description: Give the player permission to slap itself
    default: op
  playerslap.accept.others:
    description: Give the player permission to acknowledge that another player has been slapped 
    default: op
    children:
      playerslap.accept: true
  playerslap.accept:
    description: Let the player ackniwledge that it has been slapped
    default: op
  playerslap.release:
    description: Release a player who has had a permenant slap 
    default: op
  playerslap.force:
    description: Give the player permission to use the /forceslap command 
    default: op
  playerslap.noslap.protect:
    description: Slap any player who tries to slap the player with this permission 
    default: op
    children:
      playerslap.noslap: true
  playerslap.noslap:
    description: Prevent a player from being slapped 
    default: op
  playerslap.see.*:
    description: Give the player permission to see all PlayerSlap messages 
    default: op
    children:
      playerslap.see.slap: true
      playerslap.see.noslap: true
      playerslap.see.accept: true
      playerslap.see.release: true
      playerslap.see.config: true
  playerslap.see.slap:
    description: Give the player permission to see when a player has been slapped
    default: op
  playerslap.see.noslap:
    description: Give the player permission to see when a player tried to slap a player with the playerslap.noslap permission
    default: op
  playerslap.see.accept:
    description: Give the player permission to see a player's response to a slap 
    default: op
  playerslap.see.release:
    description: Give the player permission to see when a player is released from a permenant slap 
    default: op
  playerslap.see.config:
    description: Give the player permission to see config save, set and reload messages 
    default: op
  playerslap.unslap.*:
    description: Quietly remove a slap from a player 
    default: op 
    children:
      playerslap.unslap.mustaccept.decrement: true
      playerslap.unslap.ispermanent.decrement: true
  playerslap.unslap.mustaccept.decrement:
    description: Quietly remove a player's need to accept a slap and decrement its slap times counter by one 
    default: op
    children:
      playerslap.unslap.mustaccept: true
  playerslap.unslap.mustaccept:
    description: Quietly remove a player's need to accept a slap without decrementing its slap times counter 
    default: op
  playerslap.unslap.ispermanent.decrement:
    description : Quietly release a player from a permanent slap and decrement its slap times counter by one 
    default: op
    children:
      playerslap.unslap.ispermanent: true
  playerslap.unslap.ispermanent:
    description: Quietly release a player from a permanent slap without decrementing its slap times counter 
    default: op
  playerslap.config.*:
    description: Give the player access to all config file commands 
    default: op
    children: 
      playerslap.config.save: true
      playerslap.config.reload: true
      playerslap.config.newslap: true
      playerslap.config.removeslap: true
      playerslap.config.removeplayer: true
      playerslap.config.setconfig.*: true
      playerslap.config.setslap.*: true
      playerslap.config.setplayer.*: true
  playerslap.config.save:
    description: Save the config file 
    default: op
  playerslap.config.reload:
    description: Reload the config file 
    default: op
  playerslap.config.newslap:
    description: Add a new slap type 
    default: op
  playerslap.config.removeslap:
    description: Remove a slap type 
    default: op
  playerslap.config.removeplayer:
    description: Remove the information about a player 
    default: op
  playerslap.config.setconfig.*:
    description: Set general config options
    default: op
    children:
      playerslap.config.setconfig.slapself: true
      playerslap.config.setconfig.slapdefault: true
      playerslap.config.setconfig.incrementonslapall: true
  playerslap.config.setconfig.slapself:
    description: Set whether a player can slap itself 
    default: op
  playerslap.config.setconfig.slapdefault:
    description: Set the default slap type 
    default: op
  playerslap.config.setconfig.incrementonslapall:
    description: Set whether a player's slap count is incremented when the slapall command is used 
    default: op
  playerslap.config.setslap.*:
    description: Set basic config file options 
    default: op
    children:
      playerslap.config.setslap.health: true
      playerslap.config.setslap.worth: true
      playerslap.config.setslap.mustaccept: true
      playerslap.config.setslap.permanent: true
      playerslap.config.setslap.lightning: true
      playerslap.config.setslap.smoke: true
      playerslap.config.setslap.mob: true
  playerslap.config.setslap.health:
    description: Set the amount of health removed by a slap 
    default: op
  playerslap.config.setslap.worth: 
    description: Set the worth of a slap 
    default: op
  playerslap.config.setslap.mustaccept:
    description: Set whether a player must accept a slap or not 
    default: op
  playerslap.config.setslap.ispermanent:
    description: Set whether a slap is permanent or not 
    default: op
  playerslap.config.setslap.lightning:
    description: Set whether a slap produces lightning or not 
    default: op
  playerslap.config.setslap.smoke:
    description: Set the radius of smoke produced by a slap 
    default: op
  playerslap.config.setslap.mob:
    description: Set the mobs spawned by a slap 
    default: op
  playerslap.config.setplayer.*:
    description: Set basic player options 
    default: op
    children:
      playerslap.config.setplayer.times: true
      playerslap.config.setplayer.exempt: true
      playerslap.unslap.*: true
  playerslap.config.setplayer.times:
    description: Set how many times a player has been slapped 
    default: op
    children:
      playerslap.config.setplayer.times.reset: true
  playerslap.config.setplayer.times.reset:
    description: Reset how many times a player has been slapped 
    default: op
  playerslap.config.setplayer.exempt:
    description: Set whether a player is exempt from being slapped or not 
    default: op
  playerslap.info.*:
    description: Get information about slap types, players and general config information 
    default: op
    children:
      playerslap.info.slap: true
      playerslap.info.slapmessages: true
      playerslap.info.slapmobs: true
      playerslap.info.slaplist: true
      playerslap.info.player: true
      playerslap.info.general: true
  playerslap.info.slap:
    description: Get information on a type of slap 
    default: op
  playerslap.info.slapmessages:
    description: The slap specific messages sent by a slap 
    default: op
  playerslap.info.slapmobs:
    description: The mobs spawned by a slap 
    default: op
  playerslap.info.slaplist:
    description: List the available slap types 
    default: op
  playerslap.info.player:
    description: Get information on a player 
    default: op
    children:
      playerslap.info.player.times: true
  playerslap.info.player.times:
    description: Get the number of times a player has been slapped 
    default: op
  playerslap.info.general:
    description: Get general config file information 
    default: op
  playerslap.type.*:
    description: Use every slap 
    default: op
    children:
      playerslap.type.worth.*: true
      playerslap.type.noworth.*: true
  playerslap.type.anyworth.*:
    description: Use every slap with any positive worth value
    default: op
  playerslap.type.defaultworth.*:
    description: Use every slap with its specified 'worth' value 
    default: op
  playerslap.type.noworth.*:
    description: Use every slap with a 'worth' value of 0
    default: op
