slapself: true
slapdefault: 1
incrementonslapall: true
messages:
  accept: $Default
  releasebroadcast: $Default
  releasepersonal: $Default
  noreleasepersonal: $Default
slaptypes:
  '1':
    health: 3
    worth: 1
    followup:
      mustaccept: true
      permanent: false
    lightning: true
    smoke: 30
    messages:
      slapbroadcast: $Giver slapped $Slapped. 
      slappersonal: $Giver slapped you. 
      death: $Default
    mobs:
      ZOMBIE: 5
      SKELETON: 1
  '2':
    health: 5
    worth: 3
    followup:
      mustaccept: false
      permanent: false
    lightning: true
    smoke: 50
    messages:
      broadcast: $Default
      personal: $Default
      death: $Default
    mobs:
      BLAZE: 10
      GIANT: 1
      VILLAGER: 100
