slapself: true
slapdefault: '1'
incrementonslapall: true
messages:
  accept: __Default
  releasebroadcast: __Default
  releasepersonal: __Default
  noreleasepersonal: __Default
  noreleasesender: __Default
slaptypes:
  '1':
    health: 3
    worth: 1
    followup:
      mustaccept: true
      permanent: false
    lightning: true
    smoke: 30
    messages:
      slapbroadcast: __Giver slapped __Slapped. 
      slappersonal: __Giver slapped you. 
      death: __Default
    mobs:
      ZOMBIE: 5
      SKELETON: 1
  '2':
    health: 5
    worth: 3
    followup:
      mustaccept: false
      permanent: false
    lightning: true
    smoke: 50
    messages:
      broadcast: __Default
      personal: __Default
      death: __Default
    mobs:
      BLAZE: 10
      GIANT: 1
      VILLAGER: 100
