slapself: true
slapdefault: 1
incrementonslapall: true
slaptypes:
  '1':
    health: 3
    worth: 1
    followup:
      isheld: true
      mustaccept: true
    lighning: true
    smoke: 30
    messages:
      broadcast: $Giver slapped $Slapped. 
      personal: $Giver slapped you. 
      death: $Default
    mobs:
      ZOMBIE: 5
      SKELETON: 1
  '2':
    health: 5
    worth: 3
    followup:
      isheld: false
      mustaccept: false
    lightning: true
    smoke: 50
    messages:
      broadcast: $Default
      personal: $Default
      death: $Default
    mobs:
      BLAZE: 10
      GIANT: 1
      VILLAGER: 100
